version: 2
registries:
  objectcache-pro:
    type: composer-repository
    url: https://objectcache.pro/repo/
    username: token
    password: ${{secrets.OBJECTCACHE_PRO_TOKEN}}
updates:
  - package-ecosystem: composer
    directory: "/"
    registries:
      - objectcache-pro
    schedule:
      interval: daily
    open-pull-requests-limit: 99
    target-branch: main
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
