version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    target-branch: main
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
